version: "3"
services:
  api:
    image: yiisoftware/yii2-php:7.4-apache
    build: ./
    env_file:
      - .env
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - "8000:80"
    networks:
      - backend

  composer:
    restart: "no"
    image: composer:latest
    command: install
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3309:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend

networks:
  backend:
    driver: bridge
